/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main_JNIHelper */

#ifndef _Included_Main_JNIHelper
#define _Included_Main_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main_JNIHelper
 * Method:    JNITransaction
 * Signature: (Ljava/lang/String;)LMain/Main;
 */
JNIEXPORT jobject JNICALL Java_Main_JNIHelper_JNITransaction
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
