/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main_Main */

#ifndef _Included_Main_Main
#define _Included_Main_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main_Main
 * Method:    JNITransaction
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_Main_JNITransaction
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
